/**
 * The canon's placement table: what each construct does in each rendering.
 *
 * `05-internals.md` section 3 writes it as a table with three columns —
 * Article, Slides, PDF — and this module is that table as data, one row per
 * construct, quoting the brief's own words for every cell. The table, not each
 * renderer, is where a placement lives: a renderer that decided for itself
 * would be a second copy of the rule, and two copies drift.
 *
 * Reading a row is how a renderer asks "what do I do with this?". Wording is
 * kept beside the placement so a test can hold the table against the brief,
 * and so a reader of the code sees what the brief actually says.
 */

import { hasClass, type Block, type Inline } from "./tree";

/** The three renderings phase 1 to phase 6 produce. */
export type Rendering = "article" | "slides" | "print";

/** Where a construct goes in a rendering. */
export type Placement =
  /** Into the contents list and the body as a heading. */
  | "contents"
  /** Into the deck through the slide mapping. */
  | "slide-mapping"
  /** Removed before rendering, with everything inside it. */
  | "filtered"
  /** Into the flow of the text as itself. */
  | "flow"
  /** Splits the slide in force. */
  | "split"
  /** A slide whose face is the headline alone. */
  | "section-break"
  /** An appendix of sources at the end. */
  | "appendix"
  /** A slide listing the sources. */
  | "slide-of-sources"
  /** Side-by-side columns. */
  | "columns"
  /** The slide's speaker notes. */
  | "notes"
  /** Not rendered at all. */
  | "absent"
  /** A callout box. */
  | "callout"
  /** A boxed aside in the printed page. */
  | "boxed-aside"
  /** A line at the foot of the slide. */
  | "foot"
  /** A note in the margin. */
  | "margin"
  /** A note, where the rendering puts its notes. */
  | "note"
  /** A player, falling back to the poster and a link. */
  | "player"
  /** The poster and a link, printed. */
  | "poster-link"
  /** A modal, once per browser. */
  | "modal"
  /** An epigraph on the first page. */
  | "epigraph"
  /** Collectable, revealed by the Konami code. */
  | "collectable"
  /** A static aside. */
  | "aside"
  /** Read and then thrown away: no output at all. */
  | "ignored"
  /** A page break. */
  | "page-break"
  /** A numbered entry in the reference list. */
  | "numbered-reference"
  /** Generated by the renderer rather than written by the author. */
  | "generated"
  /** Honoured as written. */
  | "honoured";

/** One cell: what happens, and the brief's own words for it. */
export interface CanonCell {
  readonly placement: Placement;
  /** Quoted from `05-internals.md` section 3. */
  readonly wording: string;
}

/** One row of the placement table. */
export interface CanonRow {
  /** A stable id, used by a renderer that has no block to match. */
  readonly id: string;
  /** The construct's name, as section 3 writes it. */
  readonly construct: string;
  readonly article: CanonCell;
  readonly slides: CanonCell;
  readonly print: CanonCell;
  /**
   * The phase the construct is seeded in — the phase from which an author may
   * write it and every rendering knows what to do with it, even when what one
   * of them does is ignore it. `06-delivery.md` sets these.
   */
  readonly phase: number;
  /** Whether a block is this construct. */
  readonly matches?: (block: Block) => boolean;
  /** Whether an inline node is this construct. */
  readonly matchesInline?: (inline: Inline) => boolean;
}

/**
 * The table, in section 3's order.
 *
 * Every cell's wording is the brief's. Where the brief writes one phrase for a
 * whole row — "filtered before rendering" — every cell carries that phrase.
 */
export const CANON_ROWS: readonly CanonRow[] = [
  {
    id: "headings",
    construct: "Headings",
    article: { placement: "contents", wording: "contents and headings" },
    slides: { placement: "slide-mapping", wording: "the slide mapping" },
    print: { placement: "contents", wording: "contents and headings" },
    phase: 1,
    matches: (block) => block.kind === "heading",
  },
  {
    id: "variant",
    construct: "`variant`",
    article: { placement: "filtered", wording: "filtered before rendering" },
    slides: { placement: "filtered", wording: "filtered before rendering" },
    print: { placement: "filtered", wording: "filtered before rendering" },
    phase: 2,
    matches: (block) => hasClass(block, "variant"),
    matchesInline: (inline) => inline.kind === "span" && hasClass(inline, "variant"),
  },
  {
    id: "rule",
    construct: "Horizontal rule",
    article: { placement: "flow", wording: "a rule in the text" },
    slides: { placement: "split", wording: "splits the slide" },
    print: { placement: "flow", wording: "a rule" },
    phase: 1,
    matches: (block) => block.kind === "rule",
  },
  {
    id: "divider",
    construct: "`.divider` heading",
    article: { placement: "flow", wording: "an ordinary heading" },
    slides: { placement: "section-break", wording: "a section-break slide" },
    print: { placement: "flow", wording: "an ordinary heading" },
    phase: 1,
    matches: (block) => block.kind === "heading" && hasClass(block, "divider"),
  },
  {
    id: "refs",
    construct: "`.refs` heading",
    article: { placement: "appendix", wording: "an appendix of sources" },
    slides: { placement: "slide-of-sources", wording: "a slide of sources" },
    print: { placement: "appendix", wording: "an appendix of sources" },
    phase: 2,
    matches: (block) => block.kind === "heading" && hasClass(block, "refs"),
  },
  {
    id: "columns",
    construct: "`.columns`",
    article: { placement: "flow", wording: "ignored; content in flow" },
    slides: { placement: "columns", wording: "side-by-side columns" },
    print: { placement: "flow", wording: "ignored; content in flow" },
    phase: 1,
    matches: (block) => block.kind === "div" && hasClass(block, "columns"),
  },
  {
    id: "notes",
    construct: "`.notes`",
    article: { placement: "absent", wording: "absent" },
    slides: { placement: "notes", wording: "speaker notes" },
    print: { placement: "absent", wording: "absent" },
    phase: 1,
    matches: (block) => block.kind === "div" && hasClass(block, "notes"),
  },
  {
    id: "callout",
    construct: "`.callout`",
    article: { placement: "callout", wording: "a callout box" },
    slides: { placement: "callout", wording: "a callout box" },
    print: { placement: "boxed-aside", wording: "a boxed aside" },
    phase: 2,
    matches: (block) => block.kind === "div" && hasClass(block, "callout"),
  },
  {
    id: "credit",
    construct: "`.credit`",
    article: { placement: "margin", wording: "margin note" },
    slides: { placement: "foot", wording: "line at the foot of the slide" },
    print: { placement: "note", wording: "a note" },
    phase: 1,
    matches: (block) => block.kind === "div" && hasClass(block, "credit"),
  },
  {
    id: "margin",
    construct: "`.margin` span",
    article: { placement: "margin", wording: "margin note" },
    slides: { placement: "foot", wording: "line at the foot of the slide" },
    print: { placement: "note", wording: "a note" },
    phase: 2,
    matchesInline: (inline) => inline.kind === "span" && hasClass(inline, "margin"),
  },
  {
    id: "video",
    construct: "`.video`",
    article: { placement: "player", wording: "player, else poster and link" },
    slides: { placement: "player", wording: "player, else poster and link" },
    print: { placement: "poster-link", wording: "poster and printed link" },
    phase: 4,
    matches: (block) => block.kind === "div" && hasClass(block, "video"),
  },
  {
    id: "opening",
    construct: "`.opening`",
    article: { placement: "modal", wording: "modal, once per browser" },
    slides: { placement: "absent", wording: "absent" },
    print: { placement: "epigraph", wording: "an epigraph on the first page" },
    phase: 3,
    matches: (block) => block.kind === "div" && hasClass(block, "opening"),
  },
  {
    id: "egg",
    construct: "`.egg`",
    article: { placement: "collectable", wording: "collectable, Konami reveal" },
    slides: { placement: "absent", wording: "absent" },
    print: { placement: "aside", wording: "a static aside" },
    phase: 3,
    matches: (block) => block.kind === "div" && hasClass(block, "egg"),
    matchesInline: (inline) => inline.kind === "span" && hasClass(inline, "egg"),
  },
  {
    id: "pagebreak",
    construct: "`<!-- pagebreak -->`",
    article: { placement: "ignored", wording: "ignored" },
    slides: { placement: "ignored", wording: "ignored" },
    print: { placement: "page-break", wording: "a page break" },
    phase: 1,
    matches: (block) => block.kind === "comment" && block.comment === "pagebreak",
  },
  {
    id: "citation",
    construct: "Citation",
    article: { placement: "margin", wording: "margin note" },
    slides: { placement: "foot", wording: "credit line at the foot of the slide" },
    print: {
      placement: "numbered-reference",
      wording: "numbered reference in the list",
    },
    phase: 2,
    matchesInline: (inline) => inline.kind === "citation",
  },
  {
    id: "footnote",
    construct: "Footnote",
    article: { placement: "margin", wording: "margin note" },
    slides: { placement: "foot", wording: "line at the foot of the slide" },
    print: { placement: "note", wording: "note at the foot of the page" },
    phase: 1,
    matchesInline: (inline) =>
      inline.kind === "footnote-reference" || inline.kind === "footnote-inline",
  },
  {
    id: "reference-list",
    construct: "Reference list",
    article: { placement: "generated", wording: "generated, at the end" },
    slides: {
      placement: "absent",
      wording: "none; the deck carries credit lines only",
    },
    print: { placement: "generated", wording: "generated, numbered" },
    phase: 2,
  },
  {
    id: "image-attributes",
    construct: "Image attributes",
    article: {
      placement: "honoured",
      wording: "width and classes honoured; `.full-bleed` runs the full measure",
    },
    slides: {
      placement: "honoured",
      wording:
        "honoured on an in-flow image; an image slide is full-bleed already",
    },
    print: { placement: "honoured", wording: "width and classes honoured" },
    phase: 1,
    matches: (block) => block.kind === "image",
  },
];

/** One row by id. */
export function rowById(id: string): CanonRow | undefined {
  return CANON_ROWS.find((row) => row.id === id);
}

/**
 * The row a block belongs to, or undefined when the canon names no construct
 * for it.
 *
 * The table is read in order and the first match wins, so `## Interlude
 * {.divider}` is a divider rather than a heading: the more particular row is
 * written above the general one, as section 3 writes them.
 */
export function rowFor(block: Block): CanonRow | undefined {
  const rows = CANON_ROWS.filter((row) => row.matches?.(block) === true);
  return rows.find((row) => row.id !== "headings") ?? rows[0];
}

/** The row an inline node belongs to, if any. */
export function rowForInline(inline: Inline): CanonRow | undefined {
  return CANON_ROWS.find((row) => row.matchesInline?.(inline) === true);
}

/** Where a block goes in one rendering. */
export function placementOf(
  block: Block,
  rendering: Rendering,
): Placement | undefined {
  return rowFor(block)?.[rendering].placement;
}

/** Where an inline node goes in one rendering. */
export function inlinePlacementOf(
  inline: Inline,
  rendering: Rendering,
): Placement | undefined {
  return rowForInline(inline)?.[rendering].placement;
}
