/**
 * The slide plan: one chapter's tree read as a talk.
 *
 * The default mapping is `04-surfaces.md` section 5 — the chapter's title is
 * the opening slide, a Section is a horizontal slide, a Sub-section hangs
 * beneath it, a Sub-sub-section folds into the speaker notes, an image is a
 * slide of its own — and everything that overrides it is a row in `canon.ts`
 * rather than a branch this module invented. Nothing here renders: a plan is
 * blocks in places, and `render/slides.ts` turns places into markup.
 *
 * The plan is a value with no identity of its own. Building it twice from the
 * same text gives the same plan, and building it from new text gives the new
 * talk, which is why Present can throw the deck away and lose nothing.
 */

import { placementOf, type Placement } from "./canon";
import { slugify } from "./outline";
import { hasClass, walkInlines, type Block, type Chapter, type Inline } from "./tree";

/** What opened a slide, which is what a renderer styles it by. */
export type SlideKind =
  /** The chapter's own `#` heading. */
  | "title"
  /** A `##` heading. */
  | "section"
  /** A `###` heading, hanging beneath its Section. */
  | "subsection"
  /** A heading carrying `.divider`: the headline alone. */
  | "divider"
  /** A full-bleed image. */
  | "image"
  /** What a horizontal rule opened: no headline of its own. */
  | "continuation";

/** One line at the foot of a slide: a credit, or a footnote. */
export interface FootLine {
  readonly kind: "credit" | "footnote";
  /** A footnote's label, or null for a credit. */
  readonly label: string | null;
  /** The line's content as blocks, for a credit div or a footnote definition. */
  readonly blocks: readonly Block[];
  /** The line's content as inline nodes, for an inline footnote. */
  readonly inlines: readonly Inline[];
}

/** One slide. */
export interface Slide {
  /** Unique within the plan, and stable for the same text. */
  readonly id: string;
  readonly kind: SlideKind;
  /** The headline's plain text; empty when the slide has none. */
  readonly headline: string;
  /** The headline's inline nodes, so the renderer keeps its emphasis. */
  readonly headlineInlines: readonly Inline[];
  /** The heading level the slide came from, or null. */
  readonly level: number | null;
  /** The classes the opening heading carried, `divider` among them. */
  readonly classes: readonly string[];
  /** What the audience sees. */
  readonly face: readonly Block[];
  /** What the speaker sees. */
  readonly notes: readonly Block[];
  /** Whether the notes were generated by the mapping or written by the author. */
  readonly notesSource: "generated" | "authored";
  readonly foot: readonly FootLine[];
  /** The one-based line the slide's opening block sits on. */
  readonly line: number;
}

/** A run of slides: the first horizontal, the rest hanging beneath it. */
export interface Column {
  readonly slides: readonly Slide[];
}

/** One deck. */
export interface DeckPlan {
  /** The chapter's title, or null when it has no `#` heading. */
  readonly title: string | null;
  readonly columns: readonly Column[];
}

/** What a build may be told. */
export interface DeckOptions {
  /**
   * The variant to build. A block belonging to another variant is left out as
   * if it were not written; null builds everything, which is phase 1.
   */
  readonly variant?: string | null;
}

/** A slide under construction. */
interface Draft {
  kind: SlideKind;
  headline: string;
  headlineInlines: readonly Inline[];
  level: number | null;
  classes: readonly string[];
  line: number;
  face: Block[];
  /** The notes the mapping made. */
  generated: Block[];
  /** The notes the author wrote, or null while they have written none. */
  authored: Block[] | null;
  foot: FootLine[];
  /**
   * Where an ordinary block goes.
   *
   * A slide opened by a heading sends prose to the notes — "the audience reads
   * the headline". A slide opened by a rule sends it to the face, which is how
   * prose after a rule reaches an audience at all. An image slide inherits the
   * mode of the slide it split from, so a rule's continuation keeps its face.
   */
  mode: "face" | "notes";
}

/** The state one walk carries. */
interface Build {
  readonly columns: Draft[][];
  current: Draft | null;
  /** The axis of the innermost slide-bearing heading in force. */
  axis: "horizontal" | "vertical";
  /** Whether a Sub-sub-section is in force, folding everything into notes. */
  folding: boolean;
}

/** A fresh draft with nothing in it. */
function draft(kind: SlideKind, line: number, mode: "face" | "notes"): Draft {
  return {
    kind,
    headline: "",
    headlineInlines: [],
    level: null,
    classes: [],
    line,
    face: [],
    generated: [],
    authored: null,
    foot: [],
    mode,
  };
}

/** Whether nothing has been put on a draft yet. */
function isEmpty(slide: Draft): boolean {
  return (
    slide.face.length === 0 &&
    slide.generated.length === 0 &&
    slide.authored === null &&
    slide.foot.length === 0
  );
}

/** Start a new column with this slide: the main line of the talk advances. */
function openColumn(build: Build, slide: Draft): void {
  build.columns.push([slide]);
  build.current = slide;
}

/** Hang this slide beneath the current column: the point is unpacked. */
function hangBeneath(build: Build, slide: Draft): void {
  const column = build.columns[build.columns.length - 1];
  if (column === undefined) {
    openColumn(build, slide);
    return;
  }
  column.push(slide);
  build.current = slide;
}

/** Put a slide on the axis in force. */
function place(build: Build, slide: Draft): void {
  if (build.axis === "vertical") hangBeneath(build, slide);
  else openColumn(build, slide);
}

/** The slide in force, opening an anonymous one when there is none. */
function currentSlide(build: Build, line: number): Draft {
  if (build.current !== null) return build.current;
  const slide = draft("continuation", line, "notes");
  openColumn(build, slide);
  return slide;
}

/** Add a block to the notes the mapping is generating. */
function toNotes(build: Build, block: Block): void {
  currentSlide(build, block.line).generated.push(block);
}

/** Add a block to what the audience sees. */
function toFace(build: Build, block: Block): void {
  currentSlide(build, block.line).face.push(block);
}

/** The heading kind for a level, once the divider class has been read. */
function headingKind(level: number, divider: boolean): SlideKind {
  if (divider) return "divider";
  if (level <= 1) return "title";
  return level === 2 ? "section" : "subsection";
}

/** Open the slide a heading opens, and set the axis it puts in force. */
function openHeading(build: Build, block: Block): void {
  const level = block.level ?? 1;
  const divider = hasClass(block, "divider");
  const slide = draft(headingKind(level, divider), block.line, "notes");
  slide.headline = block.text;
  slide.headlineInlines = block.inlines;
  slide.level = level;
  slide.classes = block.attributes.classes;
  build.folding = false;
  if (level >= 3) {
    build.axis = "vertical";
    hangBeneath(build, slide);
  } else {
    build.axis = "horizontal";
    openColumn(build, slide);
  }
}

/**
 * Split at a rule.
 *
 * The continuation belongs to the Section it was split from and carries no
 * headline of its own, on the axis of the innermost slide-bearing heading in
 * force: a new column beneath the chapter title or a Section, a new vertical
 * slide beneath a Sub-section. A Sub-sub-section has no slide, so a rule
 * inside its text splits on its Sub-section's axis, which is what the axis
 * already holds.
 */
function splitAtRule(build: Build, block: Block): void {
  build.folding = false;
  place(build, draft("continuation", block.line, "face"));
}

/**
 * An image: a slide of its own, unless it is the first block of the slide in
 * force.
 *
 * The brief writes the exception as "the first block after the heading". It is
 * taken here as the first block of any slide that has nothing on it yet, so
 * that a picture opening a rule's continuation shares that slide rather than
 * making an empty one beside it. A divider shows its headline alone, so it
 * never takes the picture.
 */
function placeImage(build: Build, block: Block): void {
  const current = build.current;
  if (current !== null && current.kind !== "divider" && isEmpty(current)) {
    current.face.push(block);
    return;
  }
  const slide = draft("image", block.line, current?.mode ?? "notes");
  slide.face.push(block);
  place(build, slide);
}

/** The blocks a construct div carries, which is what the div is for. */
function contentsOf(block: Block): readonly Block[] {
  return block.children;
}

/** Whether a block belongs to the variant being built. */
function inVariant(block: Block, variant: string | null): boolean {
  if (variant === null || block.variants.length === 0) return true;
  return block.variants.includes(variant);
}

/** Put one block where the canon says it goes. */
function placeBlock(build: Build, block: Block, variant: string | null): void {
  if (!inVariant(block, variant)) return;
  const placement: Placement | undefined = placementOf(block, "slides");

  switch (placement) {
    case "filtered":
      // A variant block that survived the filter is transparent: what it holds
      // is placed as if the fence were not there, which is what lets a Section
      // belong to one variant alone.
      for (const child of block.children) placeBlock(build, child, variant);
      return;

    case "split":
      splitAtRule(build, block);
      return;

    case "section-break":
    case "slide-mapping":
    // `.refs` is not seeded in phase 1, so its heading is an ordinary heading
    // and carries its class through to the slide.
    case "slide-of-sources":
      openHeading(build, block);
      return;

    case "notes": {
      const slide = currentSlide(build, block.line);
      // The first notes div replaces the generated notes; a second one on the
      // same slide appends to the first.
      slide.authored = [...(slide.authored ?? []), ...contentsOf(block)];
      return;
    }

    case "foot": {
      const slide = currentSlide(build, block.line);
      slide.foot.push({
        kind: "credit",
        label: null,
        blocks: contentsOf(block),
        inlines: [],
      });
      return;
    }

    case "columns":
      toFace(build, block);
      return;

    case "ignored":
    case "absent":
      return;

    case "honoured":
      if (build.folding) toNotes(build, block);
      else placeImage(build, block);
      return;

    default:
      break;
  }

  // Everything else — a paragraph, a list, a table, a quote, a code block, a
  // div this phase does not know — is ordinary content.
  if (build.folding) toNotes(build, block);
  else if (currentSlide(build, block.line).mode === "face") toFace(build, block);
  else toNotes(build, block);
}

/**
 * A heading below the slide-bearing levels: no slide, everything folds.
 *
 * `03-evidence.md` records a real project with two thirds of its headings at
 * the fourth level: a main line two thirds of which is a Sub-sub-section is a
 * main line nobody can follow.
 */
function foldHeading(build: Build, block: Block): void {
  build.folding = true;
  toNotes(build, block);
}

/** Every footnote label an inline tree references, in source order. */
function footnotesIn(inlines: readonly Inline[], into: Inline[]): void {
  for (const inline of walkInlines(inlines)) {
    if (inline.kind === "footnote-reference" || inline.kind === "footnote-inline") {
      into.push(inline);
    }
  }
}

/** Every footnote a slide's own content references, definitions resolved. */
function footLinesFor(slide: Draft, chapter: Chapter): FootLine[] {
  const referenced: Inline[] = [];
  footnotesIn(slide.headlineInlines, referenced);
  const carried = [...slide.face, ...(slide.authored ?? slide.generated)];
  for (const block of carried) footnotesIn(block.inlines, referenced);
  const lines: FootLine[] = [];
  const seen = new Set<string>();
  for (const note of referenced) {
    const label = note.label ?? "";
    if (seen.has(label)) continue;
    seen.add(label);
    if (note.kind === "footnote-inline") {
      lines.push({ kind: "footnote", label, blocks: [], inlines: note.children });
      continue;
    }
    const definition = chapter.footnotes[label];
    if (definition === undefined) continue;
    lines.push({ kind: "footnote", label, blocks: definition.blocks, inlines: [] });
  }
  return lines;
}

/** Turn a finished draft into a slide, or nothing when it holds nothing. */
function finish(slide: Draft, chapter: Chapter, taken: Set<string>): Slide | null {
  const notes = slide.authored ?? slide.generated;
  const foot = [...slide.foot, ...footLinesFor(slide, chapter)];
  if (slide.headline === "" && slide.face.length === 0 && notes.length === 0 && foot.length === 0) {
    return null;
  }
  return {
    id: unique(slide.headline === "" ? "slide" : slugify(slide.headline), taken),
    kind: slide.kind,
    headline: slide.headline,
    headlineInlines: slide.headlineInlines,
    level: slide.level,
    classes: slide.classes,
    face: slide.face,
    notes,
    notesSource: slide.authored === null ? "generated" : "authored",
    foot,
    line: slide.line,
  };
}

/** Keep an id unique within one plan without changing what it means. */
function unique(id: string, taken: Set<string>): string {
  if (!taken.has(id)) {
    taken.add(id);
    return id;
  }
  let counter = 2;
  while (taken.has(`${id}-${counter}`)) counter += 1;
  const next = `${id}-${counter}`;
  taken.add(next);
  return next;
}

/** Build one chapter's columns, sharing an id pool with the rest of a deck. */
function columnsOf(
  chapter: Chapter,
  options: DeckOptions,
  taken: Set<string>,
): Column[] {
  const build: Build = { columns: [], current: null, axis: "horizontal", folding: false };
  const variant = options.variant ?? null;
  for (const block of chapter.blocks) {
    if (block.kind === "heading" && (block.level ?? 1) >= 4) {
      if (inVariant(block, variant)) foldHeading(build, block);
      continue;
    }
    placeBlock(build, block, variant);
  }
  const columns: Column[] = [];
  for (const drafts of build.columns) {
    const slides = drafts
      .map((slide) => finish(slide, chapter, taken))
      .filter((slide): slide is Slide => slide !== null);
    // A Section of one paragraph yields exactly one slide: nothing empty
    // beneath it, and no blank column after it.
    if (slides.length > 0) columns.push({ slides });
  }
  return columns;
}

/** The chapter's own title, which is its first level-one heading. */
function titleOf(chapter: Chapter): string | null {
  for (const block of chapter.blocks) {
    if (block.kind === "heading" && (block.level ?? 1) === 1) return block.text;
  }
  return null;
}

/** Build one chapter's deck. */
export function buildDeck(chapter: Chapter, options: DeckOptions = {}): DeckPlan {
  const taken = new Set<string>();
  return { title: titleOf(chapter), columns: columnsOf(chapter, options, taken) };
}

/**
 * Build one deck for a whole document, its chapters in order.
 *
 * The published deck holds the whole document; Present in the app holds the
 * chapter Alice is in. Both are the same plan, built by the same walk, so the
 * deck at the link is the deck she rehearsed.
 */
export function buildDocumentDeck(
  chapters: readonly Chapter[],
  options: DeckOptions = {},
): DeckPlan {
  const taken = new Set<string>();
  const columns: Column[] = [];
  for (const chapter of chapters) columns.push(...columnsOf(chapter, options, taken));
  const first = chapters[0];
  return { title: first === undefined ? null : titleOf(first), columns };
}

/**
 * One plan per chapter, with slide ids unique across the whole document.
 *
 * The published deck is rendered chapter by chapter, because an asset
 * resolver is bound to the Part whose folder its references sit in. The ids
 * still have to be unique across the deck: two chapters that both open with
 * "Why this matters" would otherwise both claim `#why-this-matters`, and the
 * link Alice sends would land on whichever the browser found first. So the
 * plans are built in one pass over a shared pool, exactly as
 * [`buildDocumentDeck`] does, and only the columns are kept apart.
 */
export function buildChapterDecks(
  chapters: readonly Chapter[],
  options: DeckOptions = {},
): DeckPlan[] {
  const taken = new Set<string>();
  return chapters.map((chapter) => ({
    title: titleOf(chapter),
    columns: columnsOf(chapter, options, taken),
  }));
}

/** Every slide of a plan, in the order a reader moves through them. */
export function* walkSlides(plan: DeckPlan): Generator<Slide, void, undefined> {
  for (const column of plan.columns) yield* column.slides;
}
